function [reversed] = reverse_roles_sigma(orig_sigma, numfeats)

reversed = [orig_sigma(numfeats + 1 : end, numfeats + 1 : end), ...
    orig_sigma(numfeats + 1 : end, 1 : numfeats); ...
    orig_sigma(1 : numfeats, numfeats + 1 : end), ...
    orig_sigma(1 : numfeats, 1 : numfeats)];
    
end